title = 'Guilherme Carvalho Blog'
theme = 'ananke'
languageCode = 'en-us'

defaultContentLanguage = "en"
sectionPagesMenu = "main"
enableRobotsTXT = true

[pagination]
pagerSize = 9 # this is set low for demonstrating with dummy content. Set to a higher number

# [languages.en]
# contentDir = "content/en"
# languageCode = 'en-US'
# weight = 1
# title = "Ananke"
# # languageDirection = 'rtl' for Right-To-Left languages

# [languages.fr]
# contentDir = "content/fr"
# languageCode = 'fr-FR'
# weight = 2
# title = "Ananke Fr"

[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"

[taxonomies]
  tag = "tags"
  category = "categories"

[params]
mainSections = ["post"]
text_color = ""
author = "Guilherme Carvalho" # default author, override via `author` in a posts front matter
favicon = ""
site_logo = ""
description = "The last theme you'll ever need. Maybe."
# choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
background_color_class = "bg-black"
# choose fitting and alignment styles for the featured image using Tachyons classes such as "cover|contain" for fitting and "bg-top|bg-center|bg-bottom" for alignment, or add any other class space-separated to customize further
featured_image_class = "cover bg-top"
# choose a color dimming class for the page or site header from any on this page: https://tachyons.io/docs/themes/skins/, preface it with "bg-" and add the value such as "-X0" where X is in [1,9]
cover_dimming_class = "bg-black-60"
recent_posts_number = 10

# [[menu.main]]
#   name = "Tech"
#   url = "/tech"
#   weight = 1

# [[menu.main]]
#   name = "Carreira"
#   url = "/carreira"
#   weight = 2

# [[menu.main]]
#   name = "Aprendizado"
#   url = "/aprendizado"
#   weight = 3
