baseURL = 'https://guilhermercarvalho.github.io/blog/'
title = 'Guilherme Carvalho Blog'
theme = 'ananke'
languageCode = 'en-us'
enableRobotsTXT = true

[pagination]
  pagerSize = 10

[taxonomies]
  tag = "tags"
  category = "categories"

[params]
  mainSections = ["post"]
  custom_css = ["custom.css"]
  author = "Guilherme Carvalho"
  description = "Blog técnico sobre desenvolvimento backend, arquitetura de software, DevOps e boas práticas."
  background_color_class = "bg-black"
  featured_image_class = "cover bg-top"
  cover_dimming_class = "bg-black-60"
  recent_posts_number = 10

[[menu.main]]
  name = "Posts"
  url = "/posts"
  weight = 1
[[menu.main]]
  name = "Sobre"
  url = "/about"
  weight = 2
