name: Deploy Hugo site to Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.141.0
    steps:
      - name: Install Hugo CLI
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb

      - name: Install Dart Sass
        run: sudo snap install dart-sass

      - name: Checkout main repository
        uses: actions/checkout@v4
        with:
          submodules: false  # Primeiro faz checkout sem submodules
          token: ${{ github.token }}  # Usa o GITHUB_TOKEN padrão

      - name: Configure Git credentials
        run: |
          # Configura acesso ao GitHub
          git config --global url."https://x-access-token:${{ github.token }}@github.com".insteadOf "https://github.com"

          # Configura acesso ao GitLab para submodules
          git config --global url."https://oauth2:${{ secrets.PRIVATE_SUBMODULE_TOKEN }}@gitlab.com".insteadOf "https://gitlab.com"

      - name: Update submodules
        run: git submodule update --init --recursive --remote

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Build with Hugo
        env:
          HUGO_CACHEDIR: ${{ runner.temp }}/hugo_cache
        run: |
          hugo \
            --gc \
            --minify \
            --baseURL "${{ steps.pages.outputs.base_url }}/"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
